<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>KillerMCP.Configure</AssemblyName>
    <RootNamespace>KillerMCP.Configure</RootNamespace>
    <Version>0.3.2</Version>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\KillerMCP.Clients\KillerMCP.Clients.csproj" />
  </ItemGroup>
</Project>
